name: Run Python Automation Scripts

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * 1-5'

jobs:
  run-automation:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas telebot smartapi-python pyotp ta

      - name: Execute All Python Scripts
        run: |
          python advanced_stock_screener.py
          python backtest.py
          python fetch_trades.py
          python fno_option_15min_screener.py
          python nifty_algo.py
          python nifty_algo_paper.py
          python nifty_stock_fno_master_screener.py
          python telegram_bot.py
